
spring:
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 200Mb
  datasource:
    username: Kira
    password: Kira@20021339
    url: jdbc:mysql://192.168.1.110:3306/small2?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: mysql
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none